### PR TITLE
Dutch translation results, needs DTP print-ready pdf

### PR DESCRIPTION
**Pull request by retmarut**
Lot's of extra files... they are the result of a collective effort to translate the sobtec2 corpus of articles ot the dutch language. Everything was processed, proofread and the gitbook and online books (pdf, epub and mobi) are rendering properly.

As I understood from maxigas, you have been involved in creating print-ready versions for the spanish and english translations. Was this a lot of manual work or are there some sort of short-cuts to feed the markdown docs through scribus and do some manual retouch?

Having a rough understanding of what scribus I feel relatively confident with some free time to get my head around it a bit more to start to prepare the dutch print-ready/DTP document.
In the contrib/dtp folder I have found **sobtech2-ES.sla** and it seems that this might be the way to start replacing the spanish texts with the dutch translations. Would you proceed this way or do you have suggestions to cut some corners in time and intellectual effort?

Tips and hints are really welcome!

### CODE REVIEW

**Comment by foockinho** [comment]
Hi! 

I think that replacing texts on spanish sla is the easiest way to.move. scribus needs a lot of manual attention :P 

If you need other info dont hesitate to contact me

Bests

19/8/2018 escribió:
>Lot's of extra files... they are the result of a collective effort to
>translate the sobtec2 corpus of articles ot the dutch language.
>Everything was processed, proofread and the gitbook and online books
>(pdf, epub and mobi) are rendering properly.
>
>As I understood from maxigas, you have been involved in creating
>print-ready versions for the spanish and english translations. Was this
>a lot of manual work or are there some sort of short-cuts to feed the
>markdown docs through scribus and do some manual retouch?
>
>Having a rough understanding of what scribus I feel relatively
>confident with some free time to get my head around it a bit more to
>start to prepare the dutch print-ready/DTP document.
>In the contrib/dtp folder I have found **sobtech2-ES.sla** and it seems
>that this might be the way to start replacing the spanish texts with
>the dutch translations. Would you proceed this way or do you have
>suggestions to cut some corners in time and intellectual effort?
>
>Tips and hints are really welcome!
> 
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/foockinho/sobtec2/pull/1
>
>-- Commit Summary --
>
>  * First tentative try at multi language setup
>  * Test headlines
>  * Translate table of contents
>* Add second and third batch of English translations, including the
>LEAP text from the first batch that was left behind
>  * Corrections to README.md
>  * More corrections to README.md
>  * Fix footnotes in README.md according to gitbook syntax
>  * Add last missing articles
>  * Double checking: First small corrections
>  * See if leaks footnotes render correctly
>  * See if leaks footnotes render correctly, again
>  * More small corrections
>* Restore lost footnotes to COATI article, and other small
>modifications
>* Numbers instead of alphanumeric IDs for footnotes in the COATI
>article
>* Small updates, new version of IRC article, first stay at readable
>footnotes in the coop article
>* Trying to fuzz their multiline footnote syntax because the gitbook
>documentation is vague
>  * OK, coop articles has no multiline footnotes now
>  * Stubs for contributions, acknowledgements and back cover files
>  * Add sketches to /contrib
>* Bullet points instead of semicolons for long footnote URL lists in
>coop article
>* Make sure titles and authors are rendered with the same formatting in
>all English chapters
>  * Add rendered output files
>  * Internationalisation!
>  * Add slides from hackon.nl to /contrib
>  * Move hackon slides to a hackon directory
>  * Add licence
>  * Rename licence file to conform to github conventions
>  * Rename licence file to conform to github conventions, spelling
>  * Consistent capitalisation in algos article headlines
>  * Clarify the purpose of web of trust because author asked for it
>* Render pandoc-markdown citations in IRC article and keep the original
>file with .pan extension
>  * Unfill bibliography in IRC article
>  * Remove DIV tags from IRC article
>  * Delete Changelog of English proofreading
>  * Add English dedication
>  * Add credits
>  * Change 'credits' to 'contributions'
>  * Correct wording in Contributions
>  * Correct capitalisation in title
>* Put FIXME for article title in contributions that is unknown at the
>moment
>  * Add Contributions page to es and fr version
>  * Add Dedications
>  * Final order of English articles
>  * Final chapter titles, all languages
>* Add logo and full French content, but French content needs formatting
>* Make language selection page more international by removing header in
>English
>  * First stab at French intro
>  * Correct identation in English Table of Contents
>  * Correct original language table of contents order of articles
>  * First half of French articles formatted
>  * French Table of Contents
>  * Touch up French articles, part 1. and backport changes to English
>  * See if conversations look better in French rats article
>  * See if conversations look better in French rats article II.
>* See if conversations look better in French rats article with EM
>dashes.
>  * French rizomatika article preview
>  * French rats article touchup conversation formatting
>  * Fix rizomatica French article formatting and footnotes
>  * Touch up rizomatica and coati articles in multiple languages
>* Touch up rizomatica articles in multiple languages: Last footnote was
>missing and double spaces were in the text, one footnote was wrong,
>etc.
>  * Fix heading capitalisation in coati French article
>  * All French articles
>  * Small correction mainly to French articles
>* Make sure authors are specified and formatted correctly in English
>and French
>  * Delete temporary file
>  * Half of Spanish edition and all print current releases
>* More three Spanish articles and backport of some changes to English
>versions
>  * Tidy Spanish Table of Contents
>  * Mainly the Spanish coop article formatting
>  * Spanish version almost finished and backported many changes
>  * Formatting Spanish version complete
>  * Synchronise credits pages in all languages
>  * Synchronise credits pages in all languages, polish
>* Add a ruler to the French intro where it is in other language
>versions
>  * Add French and English web release PDFs with covers
>  * Add gfx dirs from the printed versions
>  * Fix illustrations file names and provide half sized versions
>  * Try inserting illustration to an article
>  * Add English illustrations to the English book
>  * Add illustrations to the Spanish book and corrections to English
>  * Add illustrations to the French book
>* Update original language version of the book using links to actual
>language versions
>  * Poke gitbook to see if it updates
>  * Correct links in the summary of the original language version
>* Correct links in the summary of the original language version, now
>with copied files, because linking from other language version did not
>work
>  * Add sfx from Congress
>  * Update web releases
>  * add reviewed spanish translation
>  * Update README.md in all language versions
>  * Update web releases and covers
>  * Update quotation marks in README.md versions
>  * Update gitbook render releases
>* Update links to different format releases in README.md in all
>language versions
>  * Remove temporary file
>* Update links to scribus-exported PDFs in README.md in all language
>versions
>  * Name languages in English in English README.md
>  * Fix front cover instead of back cover in Spanish web release
>  * Merge pull request #1 from kalikaneko/master
>  * Fix reviewed Spanish translation formatting
>  * Update Spanish web version with Kali corrected article
>  * Update Spanish print version with Kali corrected article
>  * Various small updates after French digital version review
>  * Fix !2 (issue number two): Spelling mistake
>  * Fix links in README.md files to language versions
>  * Add gitbooks script
>  * Update gitbook releases with local gitbook script results
>  * Fix broken link to Spanish web edition
>  * traduzione italiana
>  * traduzione capitolo 7
>  * traduzione di largo
>  * Fix Spanish readme typos
>  * Fix Spanish summary
>  * Add ePub covers
>  * Fix ePub metadata
>  * Update 'it/content/06coops.md'
>* [it]08Un seme germoglia quando è seminato in un terreno fertile 
>Loreto Bravo
>  * IT Ippolit apedagogia hacker
>  * traduzione
>  * Update sobtec2es print version
>  * Add sobtec2es desktop publishing source for editing with Scribus
>  * summary e largo trad
>* Merge branch 'master' of
>git.lattuga.net:hacklabbo/soberania_tecnologicaV2
>  * piccola modifica
>  * escludo file compilati del libro
>  * Merge pull request #5 from Roboe/spanish-proofread
>  * Merge pull request #3 from Roboe/epub-covers
>  * Merge pull request #4 from Roboe/epub-fix-metadata
>  * Merge ssh://git.lattuga.net/hacklabbo/soberania_tecnologicaV2
>  * first nl translation
>  * Dutch translations
>  * initial, needs proofreading
>  * credits.md
>  * credits.md
>  * revert to en
>  * nl translation
>  * editor change
>  * initial translation, needs proofreading!
>  * Set theme jekyll-theme-minimal
>  * typofix
>  * Partial translation of meta-docs
>  * Merge branch 'master' of https://github.com/retmarut/sobtec2
>  * pretranslated effort to ease selection for volunteers
>  * eerste vertaalde versie
>  * Bijdrage Kel
>  * Merge pull request #1 from sobteclib/master
>  * Update gitbook releases with local gitbook script results
>  * extra translated texts
>  * first translation
>  * Remove FEFF unicode char
>  * removal of intermediate file
>  * remove html tags from md
>  * Merge pull request #2 from KwadroNaut/master
>  * Merge pull request #3 from KwadroNaut/patch-1
>  * [WIP]
>  * Rizomatica NL-translation
>  * NL entrypage
>  * old irc translation
>  * Merge pull request #4 from KwadroNaut/09-nl
>  * rizo layout extras
>  * added italiano
>  * proofreading done
>  * old text
>  * title translations
>  * typo fix
>  * typo fix
>  * titel hervertaald
>  * correcting mistaken typo-fix
>  * Update 11leap.md
>  * Update 11leap.md
>  * Update 10leaks.md
>  * Merge pull request #5 from L-Kraft/patch-1
>  * Merge pull request #6 from L-Kraft/patch-3
>  * summary corrections
>  * typofix
>  * typo has/was
>  * Merge pull request #7 from KwadroNaut/typo
>  * intro nl translation
>  * Merge branch 'master' of github.com:retmarut/sobtec2
>* footnote added for special economic zone. Needs expansion in other
>translations too
>  * Redaction ref correction
>  * proofreading done
>  * initial proofread translation
>  * typo and layoyt fixes
>  * footnote fixes
>  * Rename 04gamifiation.md to 04gamification.md
>  * More proofreading revealed lots of typos
>  * Update README.md
>  * Update README.md
>  * typo fix
>  * Soevereiniteit everywhere
>  * nog meer Soevereinieit; correcte spelling
>  * typofix
>  * algos first corrected translation, needs fixing...
>  * Typo and footnote fixes
>  * Update 01preface.md
>  * Update 01preface.md
>  * Update 01preface.md
>  * Update 01preface.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * Update 02intro.md
>  * teruggezet
>* Merge branch 'master' of https://github.com/misteek/sobtec2 into
>misteek-master
>  * Merge branch 'misteek-master'
>  * Merge pull request #1 from retmarut/master
>  * Update 04gamification.md
>  * Update 05irc.md
>  * Update 08rizomatica.md
>  * Update README.md
>  * Update 01preface.md
>  * kleine typo's
>  * Correcties tot aan 'Algoritmen die publieke data vreten'
>  * Update 09coati.md
>  * Update 10leaks.md
>  * Update 11leap.md
>  * Merge pull request #10 from misteek/patch-5
>  * Merge pull request #15 from misteek/patch-9
>  * Merge pull request #14 from misteek/patch-8
>  * Merge pull request #13 from misteek/patch-7
>  * Merge pull request #11 from misteek/patch-6
>  * Merge pull request #9 from misteek/patch-4
>  * Merge pull request #12 from L-Kraft/master
>  * Herstelde versie met markdown
>  * Merge branch 'master' of github.com:retmarut/sobtec2
>  * Nederlandstalige links naar wikipedia
>  * Comment correct afgebroken
>  * typofixes, proofreading is gedaan
>  * proofreading the proofreading
>  * gitbook modif
>  * undo previous modif
>  * subtle markdown changes
>  * Merge pull request #16 from retmarut/gitbook-repair-initiative
>  * removed italiano
>  * removed disfunctional remnants of yekyll experiments
>  * Update gitbook releases with local gitbook script results
>  * dutch_pdf
>* Merge pull request #17 from
>retmarut/origin/footnotes-linkrot-detection-effort
>  * backcover json content
>  * backcover json content
>* Merge pull request #18 from
>retmarut/origin/footnotes-linkrot-detection-effort
>
>-- File Changes --
>
>    A .gitignore (4)
>    A LANGS.md (8)
>    D LICENSE (116)
>    A LICENSE.txt (438)
>    D README.md (2)
>    D SUMMARY.md (29)
>    D book.json (9)
>    D content/03algos.md (202)
>    D content/05coati.md (97)
>    D content/06leaks.md (93)
>    D content/08leap.md (353)
>    D content/09irc.md (107)
>    D content/10gamification.md (84)
>    D content/12cooperativas.md (422)
>    A contrib/dtp/sobtech2-ES.sla (12361)
>    A contrib/gfx/calafou/pagina-carteles600ppp.png (0)
>    A contrib/gfx/calafou/pagina-fotos600ppp.png (0)
>    A contrib/gfx/covers/tapa-EN-600dpi.png (0)
>    A contrib/gfx/covers/tapa-ES-600dpi.png (0)
>    A contrib/gfx/covers/tapa-FR-600dpi.png (0)
>    A contrib/gfx/covers/tapa-ok-EN-final-sangre.pdf (0)
>    A contrib/gfx/covers/tapa-ok-EN-final-sangre.svg (23166)
>    A contrib/gfx/covers/tapa-ok-EN-final.svg (23173)
>    A contrib/gfx/covers/tapa-ok-ES-final-sangre.pdf (0)
>    A contrib/gfx/covers/tapa-ok-ES-final.svg (13954)
>    A contrib/gfx/illustrations/algoritmos-halfsize.png (0)
>    A contrib/gfx/illustrations/algoritmos.png (0)
>    A contrib/gfx/illustrations/algoritmos.svg (113)
>    A contrib/gfx/illustrations/chatons-halfsize.png (0)
>    A contrib/gfx/illustrations/chatons.png (0)
>    A contrib/gfx/illustrations/chatons.svg (612)
>    A contrib/gfx/illustrations/coati-halfsize.png (0)
>    A contrib/gfx/illustrations/coati.png (0)
>    A contrib/gfx/illustrations/coati.svg (699)
>    A contrib/gfx/illustrations/digital-governance-halfsize.png (0)
>    A contrib/gfx/illustrations/digital-governance.png (0)
>    A contrib/gfx/illustrations/digital-governance.svg (205)
>    A contrib/gfx/illustrations/hacktocoop.svg (234)
>    A contrib/gfx/illustrations/hacktocoops-halfsize.png (0)
>    A contrib/gfx/illustrations/hacktocoops.png (0)
>    A contrib/gfx/illustrations/intro-halfsize.png (0)
>    A contrib/gfx/illustrations/intro.png (0)
>    A contrib/gfx/illustrations/intro.svg (1186)
>    A contrib/gfx/illustrations/irc-halfsize.png (0)
>    A contrib/gfx/illustrations/irc.png (0)
>    A contrib/gfx/illustrations/irc.svg (358)
>    A contrib/gfx/illustrations/leap-halfsize.png (0)
>    A contrib/gfx/illustrations/leap.png (0)
>    A contrib/gfx/illustrations/leap.svg (594)
>    A contrib/gfx/illustrations/prefacio-halfsize.png (0)
>    A contrib/gfx/illustrations/prefacio.png (0)
>    A contrib/gfx/illustrations/prefacio.svg (183)
>    A contrib/gfx/illustrations/rhyzomatica-halfsize.png (0)
>    A contrib/gfx/illustrations/rhyzomatica.png (0)
>    A contrib/gfx/illustrations/rhyzomatica.svg (121)
>    A contrib/gfx/illustrations/tecnoaprop-halfsize.png (0)
>    A contrib/gfx/illustrations/tecnoaprop.png (0)
>    A contrib/gfx/illustrations/tecnoaprop.svg (299)
>    A contrib/gfx/illustrations/whistleblowing-halfsize.png (0)
>    A contrib/gfx/illustrations/whistleblowing.png (0)
>    A contrib/gfx/illustrations/whistleblowing.svg (554)
>    A contrib/gfx/sketches/algoritmos.png (0)
>    A contrib/gfx/sketches/chatonspre.png (0)
>    A contrib/gfx/sketches/coati-test.png (0)
>    A contrib/gfx/sketches/gamification-ippolita.png (0)
>    A contrib/gfx/sketches/gamification-ippolita2.png (0)
>    A contrib/gfx/sketches/global-leaks.png (0)
>    A contrib/gfx/sketches/irc2.png (0)
>    A contrib/gfx/sketches/rhyzomatica.png (0)
>    A contrib/gfx/sketches/tecno-aprop.png (0)
>    A contrib/sfx/README.md (6)
>    A contrib/sfx/SobTec2_CCC.ogg (0)
>    A contrib/slides/2017hackon.nl/compile.sh (2)
>    A contrib/slides/2017hackon.nl/images/barrirack.png (0)
>    A contrib/slides/2017hackon.nl/images/calafou0.jpg (0)
>    A contrib/slides/2017hackon.nl/images/cover.png (0)
>    A contrib/slides/2017hackon.nl/images/detail.png (0)
>    A contrib/slides/2017hackon.nl/images/digibooks.png (0)
>    A contrib/slides/2017hackon.nl/images/livinglab.png (0)
>    A contrib/slides/2017hackon.nl/index.html (243)
>    A contrib/slides/2017hackon.nl/reveal.js (1)
>    A contrib/slides/2017hackon.nl/slides.md (165)
>    A en/README.md (19)
>    A en/SUMMARY.md (29)
>    A en/book.json (9)
>    A en/content/00dedication.md (7)
>    A en/content/01preface.md (322)
>    A en/content/02intro.md (313)
>    A en/content/03algos.md (468)
>    A en/content/04gamification.md (362)
>    A en/content/05irc.md (423)
>    R en/content/05irc.pan (55)
>    A en/content/06cooperatives.md (281)
>    A en/content/07rats.md (405)
>    A en/content/08rizomatica.md (335)
>    A en/content/09coati.md (338)
>    A en/content/10leaks.md (265)
>    A en/content/11leap.md (344)
>    A en/content/12chatons.md (387)
>    A en/content/13credits.md (59)
>    R en/content/14back.md (0)
>    A en/content/_filedir (344)
>    A en/cover.jpg (0)
>    A es/README.md (21)
>    A es/SUMMARY.md (29)
>    A es/book.json (9)
>    A es/content/00dedicacion.md (3)
>    R es/content/01prefacio.md (176)
>    A es/content/02intro.md (330)
>    A es/content/03algos.md (468)
>    A es/content/04gamification.md (412)
>    A es/content/05irc.md (424)
>    A es/content/06coops.md (315)
>    A es/content/07rats.md (431)
>    A es/content/08rizo.md (360)
>    A es/content/09coati.md (385)
>    A es/content/10leaks.md (301)
>    A es/content/11leap.md (383)
>    A es/content/12chatons.md (429)
>    A es/content/13creditos.md (56)
>    R es/content/14back.md (0)
>    R es/content/old/07apropriadas.md (68)
>    R es/content/old/08rhyzomatica.md (30)
>    A es/cover.jpg (0)
>    A fr/README.md (21)
>    A fr/SUMMARY.md (32)
>    A fr/book.json (9)
>    A fr/content/00devoument.md (4)
>    A fr/content/01preface.md (359)
>    A fr/content/02intro.md (352)
>    A fr/content/03algos.md (204)
>    A fr/content/04gamification.md (436)
>    A fr/content/05irc.md (381)
>    A fr/content/06cooperatives.md (336)
>    A fr/content/07rats.md (459)
>    A fr/content/08rizomatica.md (384)
>    A fr/content/09coati.md (398)
>    A fr/content/10leaks.md (305)
>    A fr/content/11leap.md (406)
>    R fr/content/12chatons.md (36)
>    A fr/content/13credits.md (57)
>    R fr/content/14couverture.md (0)
>    A fr/cover.jpg (0)
>    A it/Nota per le traduzioni (8)
>    A it/README.md (0)
>    A it/SUMMARY.md (29)
>    A it/content/04gamification.md (0)
>    A it/content/05irc.md (0)
>    A it/content/06coops.md (0)
>    A it/content/07rats.md (0)
>    A it/content/08rizo.md (0)
>    A logo.png (0)
>    A nl/README.md (0)
>    A nl/SUMMARY.md (0)
>    A nl/book.json (0)
>    A nl/content/00dedication.md (0)
>    A nl/content/01preface.md (0)
>    A nl/content/02intro.md (0)
>    A nl/content/03algos.md (0)
>    A nl/content/04gamification.md (0)
>    A nl/content/05irc.md (0)
>    A nl/content/06cooperatives.md (0)
>    A nl/content/07rats.md (0)
>    A nl/content/08rizomatica.md (0)
>    A nl/content/09coati.md (0)
>    A nl/content/10leaks.md (0)
>    A nl/content/11leap.md (0)
>    A nl/content/12chatons.md (0)
>    A nl/content/13credits.md (0)
>    A nl/content/14back.md (0)
>    A nl/cover.jpg (0)
>    A or/README.md (0)
>    A or/SUMMARY.md (0)
>    A or/book.json (0)
>    A or/content/01prefacio.md (0)
>    A or/content/02intro.md (0)
>    A or/content/03algos.md (0)
>    A or/content/04gamification.md (0)
>    A or/content/05irc.md (0)
>    A or/content/06cooperatives.md (0)
>    A or/content/07rats.md (0)
>    A or/content/08rizo.md (0)
>    A or/content/09coati.md (0)
>    A or/content/10leaks.md (0)
>    A or/content/11leap.md (0)
>    A or/content/12chatons.md (0)
>    A or/content/13creditos.md (0)
>    A or/content/14back.md (0)
>    A or/cover.jpg (0)
>    A releases/latest/sobtec2_en.epub (0)
>    A releases/latest/sobtec2_en.mobi (0)
>    A releases/latest/sobtec2_en.pdf (0)
>    A releases/latest/sobtec2_es.epub (0)
>    A releases/latest/sobtec2_es.mobi (0)
>    A releases/latest/sobtec2_es.pdf (0)
>    A releases/latest/sobtec2_fr.epub (0)
>    A releases/latest/sobtec2_fr.mobi (0)
>    A releases/latest/sobtec2_fr.pdf (0)
>    A releases/latest/sobtec2_nl.epub (0)
>    A releases/latest/sobtec2_nl.mobi (0)
>    A releases/latest/sobtec2_nl.pdf (0)
>    A releases/latest/sobtec2_or.epub (0)
>    A releases/latest/sobtec2_or.mobi (0)
>    A releases/latest/sobtec2_or.pdf (0)
>    A releases/print/ebook_manual-de-scribus-1.3.3.pdf (0)
>    A releases/print/scribus-manual-de-usuario.pdf (0)
>    A releases/print/sobtec1a5final/a.pdf (0)
>    A releases/print/sobtec1a5final/inside.pdf (0)
>    A releases/print/sobtec1a5final/outside.pdf (0)
>    A releases/print/sobtech2-EN-2017-12-10-V2.pdf (0)
>    A releases/print/sobtech2-ES-2018-02-20-PRINT.pdf (0)
>    A releases/print/tapa-ok-EN-final-sangre.pdf (0)
>    A releases/print/tapa-ok-ES-final-sangre.pdf (0)
>A releases/web/sobtech2-EN-with-covers-web-150dpi-2018-01-10-v2.pdf (0)
>A releases/web/sobtech2-ES-with-covers-web-150dpi-2018-01-13-v2.pdf (0)
>A releases/web/sobtech2-FR-with-covers-web-150dpi-2018-01-10-v2.pdf (0)
>    A scripts/gitbooks.sh (0)
>
>-- Patch Links --
>
>https://github.com/foockinho/sobtec2/pull/1.patch
>https://github.com/foockinho/sobtec2/pull/1.diff

**Comment by retmarut** [comment]
Currently I am investigation the path along pandoc-latex-pdf
Preliminary output of sepeare docs looks good (and is easy)
Getting the docs collated into 1 doc preclucing it with a TOC, cratfitng the front/back cover with spine is something to work on.

**Comment by retmarut** [comment]
How did you get the ISBN number generated?

**Comment by foockinho** [comment]
We bought it on the spanish isbn vendor, its needed for each language (45e) 

19/8/2018 escribió:
>How did you get the ISBN number generated?

**Comment by retmarut** [comment]
I have opened another more narrow pull requests to work on the cover. With that this pull request is not really too relevant. Closing it...

**Pull request closed without merging**
